language: python

matrix:
  include:
    - python: 2.7
      dist: trusty
      sudo: false
    - python: 3.4
      dist: trusty
      sudo: false
    - python: 3.5
      dist: trusty
      sudo: false
    - python: 3.6
      dist: trusty
      sudo: false
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 2.7
      arch: arm64
      dist: trusty
      sudo: false
    - python: 3.7
      arch: arm64
      dist: xenial
      sudo: false

before_install:
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
      echo "No pull requests can be sent to the master branch" 1>&2;
      exit 1;
    fi
install:
  - python scripts/ci/install
script: python scripts/ci/run-tests
